version: '3.9'
services:
  app:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        NEXT_PUBLIC_CLIENTVAR: 'clientvar'
        GIT_ACCESS_TOKEN: ${GIT_ACCESS_TOKEN}
    working_dir: /app
    command: yarn dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    image: t3-app
    env_file:
      - .env
