version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    command: yarn dev
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/template-app
      - NEXTAUTH_SECRET=something-secret
      - NEXTAUTH_URL=http://localhost:3000